
import { formatRoad, RoadDescriptor } from "./components/road3d";

export const testRoad:RoadDescriptor = {
    roadSegments: formatRoad([
        { curve: 0 },
        { curve: 0 },
        { curve: 0 },
        { curve: 0 },
        { curve: 0 },
        { curve: 0 },
        { curve: 0 },
        { curve: 0 },
        { curve: 0 },
        { curve: 0 },

        { curve: 0 },
        { curve: 0 },
        { curve: 0 },
        { curve: 0 },
        { curve: 0 },
        { curve: 0 },
        { curve: 0 },
        { curve: 0 },
        { curve: 0 },
        { curve: 0 },

        { curve: 0 },
        { curve: 0 },
        { curve: 0 },
        { curve: 0 },
        { curve: 0 },
        { curve: 0 },
        { curve: 0 },
        { curve: 0 },
        { curve: 0 },
        { curve: 0 },

        { curve: 0 },
        { curve: 0 },
        { curve: 0 },
        { curve: 0 },
        { curve: 0 },
        { curve: 0 },
        { curve: 0 },
        { curve: 0 },
        { curve: 0 },
        { curve: 0 },

        { curve: 0.5 },
        { curve: 1.0 },
        { curve: 1.5 },
        { curve: 2.5 },
        { curve: 4.0 },
        { curve: 4.5 },
        { curve: 5 },
        { curve: 5 },
        { curve: 5 },
        { curve: 5 },

        { curve: 5 },
        { curve: 5 },
        { curve: 5 },
        { curve: 5 },
        { curve: 5 },
        { curve: 5 },
        { curve: 5 },
        { curve: 5 },
        { curve: 5 },
        { curve: 5 },
        
        { curve: 5 },
        { curve: 5 },
        { curve: 4.5 },
        { curve: 4.0 },
        { curve: 3.0 },
        { curve: 2.0 },
        { curve: 1.0 },
        { curve: 0 },
        { curve: -0.5 },
        { curve: -1.5 },

        { curve: -2 },
        { curve: -2 },
        { curve: -2 },
        { curve: -2 },
        { curve: -2 },
        { curve: -2 },
        { curve: -2 },
        { curve: -2 },
        { curve: -2 },
        { curve: -2 },

        { curve: -2 },
        { curve: -2 },
        { curve: -2 },
        { curve: -2 },
        { curve: 0 },
        { curve: 0 },
        { curve: 0 },
        { curve: 0 },
        { curve: 0 },
        { curve: 0 },
        
        { curve: 0 },
        { curve: -1 },
        { curve: -1 },
        { curve: -1 },
        { curve: -1 },
        { curve: -1 },
        { curve: -1 },
        { curve: -1 },
        { curve: -1 },
        { curve: -1 },

        { curve: -1 },
        { curve: -1.5 },
        { curve: -1.5 },
        { curve: -1.5 },
        { curve: -1.5 },
        { curve: -1.5 },
        { curve: -1.5 },
        { curve: -1.5 },
        { curve: -1.5 },
        { curve: -1.5 },

        { curve: 1.5 },
        { curve: 1.5 },
        { curve: 1.5 },
        { curve: 1.5 },
        { curve: 1.5 },
        { curve: 1.5 },
        { curve: 1.5 },
        { curve: 1.5 },
        { curve: 1.5 },
        { curve: 0 }
    ]),
    roadObjects: [
        { type: "sign", props: {z:5, header: "Hello World"}, 
            content: [
                "Here's some dynamic sign content:", 
                "Eventually, this will be the real sign contents!",
                "Some more sign contents, just for you!",
            ]
        },
        { type: "sign", props: {z:7, header: "Test 2!"}, 
            content: ["I'm a second tester!"]
        }
    ]
}
