
import { RoadSegmentDescriptor } from "./components/road3d/utils";

export const roadSegments:RoadSegmentDescriptor = [
    { curve: 0 },
    { curve: 0 },
    { curve: 0 },
    { curve: 0 },
    { curve: 0 },
    { curve: 0 },
    { curve: 0 },
    { curve: 0 },
    { curve: 0 },
    { curve: 0 },

    { curve: 0 },
    { curve: 0 },
    { curve: 0 },
    { curve: 0 },
    { curve: 0 },
    { curve: 0 },
    { curve: 0 },
    { curve: 0 },
    { curve: 0 },
    { curve: 0 },

    { curve: 0 },
    { curve: 0 },
    { curve: 0 },
    { curve: 0 },
    { curve: 0 },
    { curve: 0 },
    { curve: 0 },
    { curve: 0 },
    { curve: 0 },
    { curve: 0 },

    { curve: 0 },
    { curve: 0 },
    { curve: 0 },
    { curve: 0 },
    { curve: 0 },
    { curve: 0 },
    { curve: 0 },
    { curve: 0 },
    { curve: 0 },
    { curve: 0 },

    { curve: 0.5 },
    { curve: 1.0 },
    { curve: 1.5 },
    { curve: 2.5 },
    { curve: 4.0 },
    { curve: 4.5 },
    { curve: 5 },
    { curve: 5 },
    { curve: 5 },
    { curve: 5 },

    { curve: 5 },
    { curve: 5 },
    { curve: 5 },
    { curve: 5 },
    { curve: 5 },
    { curve: 5 },
    { curve: 5 },
    { curve: 5 },
    { curve: 5 },
    { curve: 5 },
    
    { curve: 5 },
    { curve: 5 },
    { curve: 4.5 },
    { curve: 4.0 },
    { curve: 3.0 },
    { curve: 2.0 },
    { curve: 1.0 },
    { curve: 0 },
    { curve: -0.5 },
    { curve: -1.5 },

    { curve: -2 },
    { curve: -2 },
    { curve: -2 },
    { curve: -2 },
    { curve: -2 },
    { curve: -2 },
    { curve: -2 },
    { curve: -2 },
    { curve: -2 },
    { curve: -2 },

    { curve: -2 },
    { curve: -2 },
    { curve: -2 },
    { curve: -2 },
    { curve: 0 },
    { curve: 0 },
    { curve: 0 },
    { curve: 0 },
    { curve: 0 },
    { curve: 0 },
    
    { curve: 0 },
    { curve: -1 },
    { curve: -1 },
    { curve: -1 },
    { curve: -1 },
    { curve: -1 },
    { curve: -1 },
    { curve: -1 },
    { curve: -1 },
    { curve: -1 },

    { curve: -1 },
    { curve: -1.5 },
    { curve: -1.5 },
    { curve: -1.5 },
    { curve: -1.5 },
    { curve: -1.5 },
    { curve: -1.5 },
    { curve: -1.5 },
    { curve: -1.5 },
    { curve: -1.5 },

    { curve: 1.5 },
    { curve: 1.5 },
    { curve: 1.5 },
    { curve: 1.5 },
    { curve: 1.5 },
    { curve: 1.5 },
    { curve: 1.5 },
    { curve: 1.5 },
    { curve: 1.5 },
    { curve: 0 }
]
