
import { RoadSegmentDescriptor } from "./components/road3d/utils";
import { ObjectTypes } from "./components/objects3d";

export const roadSegments:RoadSegmentDescriptor = [
    { curve: 0 },
    { curve: 0 },
    { curve: 0 },
    { curve: 0 },
    { curve: 0 },
    { curve: 0 },
    { curve: 0 },
    { curve: 0 },
    { curve: 0 },
    { curve: 0 },

    { curve: 0 },
    { curve: 0 },
    { curve: 0 },
    { curve: 0 },
    { curve: 0 },
    { curve: 0 },
    { curve: 0 },
    { curve: 0 },
    { curve: 0 },
    { curve: 0 },

    { curve: 0 },
    { curve: 0 },
    { curve: 0 },
    { curve: 0 },
    { curve: 0 },
    { curve: 0 },
    { curve: 0 },
    { curve: 0 },
    { curve: 0 },
    { curve: 0 },

    { curve: 0 },
    { curve: 0 },
    { curve: 0 },
    { curve: 0 },
    { curve: 0 },
    { curve: 0 },
    { curve: 0 },
    { curve: 0 },
    { curve: 0 },
    { curve: 0 },

    { curve: 0.5 },
    { curve: 1.0 },
    { curve: 1.5 },
    { curve: 2.5 },
    { curve: 4.0 },
    { curve: 4.5 },
    { curve: 5 },
    { curve: 5 },
    { curve: 5 },
    { curve: 5 },

    { curve: 5 },
    { curve: 5 },
    { curve: 5 },
    { curve: 5 },
    { curve: 5 },
    { curve: 5 },
    { curve: 5 },
    { curve: 5 },
    { curve: 5 },
    { curve: 5 },
    
    { curve: 5 },
    { curve: 5 },
    { curve: 4.5 },
    { curve: 4.0 },
    { curve: 3.0 },
    { curve: 2.0 },
    { curve: 1.0 },
    { curve: 0 },
    { curve: -0.5 },
    { curve: -1.5 },

    { curve: -2 },
    { curve: -2 },
    { curve: -2 },
    { curve: -2 },
    { curve: -2 },
    { curve: -2 },
    { curve: -2 },
    { curve: -2 },
    { curve: -2 },
    { curve: -2 },

    { curve: -2 },
    { curve: -2 },
    { curve: -2 },
    { curve: -2 },
    { curve: 0 },
    { curve: 0 },
    { curve: 0 },
    { curve: 0 },
    { curve: 0 },
    { curve: 0 },
    
    { curve: 0 },
    { curve: -1 },
    { curve: -1 },
    { curve: -1 },
    { curve: -1 },
    { curve: -1 },
    { curve: -1 },
    { curve: -1 },
    { curve: -1 },
    { curve: -1 },

    { curve: -1 },
    { curve: -1.5 },
    { curve: -1.5 },
    { curve: -1.5 },
    { curve: -1.5 },
    { curve: -1.5 },
    { curve: -1.5 },
    { curve: -1.5 },
    { curve: -1.5 },
    { curve: -1.5 },

    { curve: 1.5 },
    { curve: 1.5 },
    { curve: 1.5 },
    { curve: 1.5 },
    { curve: 1.5 },
    { curve: 1.5 },
    { curve: 1.5 },
    { curve: 1.5 },
    { curve: 1.5 },
    { curve: 0 }
]

export const RoadObjects:ObjectTypes[] = [
    { type: "sign", props: {z:5, header: "Hello World"}, 
        content: "Ultimately, this will be the sign contents!"
    },
    { type: "sign", props: {z:7, header: "Test 2!"}, 
        content: "I'm a second tester!"
    }
]
